### ISSUE TITLE
USing A diffrent SMTP SERVER

### ISSUE THREAD

**Issue by Bugspiderlee** [naschorr/mail-to-sms#7]
Hi how do u specify a diffrent mail server address  

lets say i use this command
mail_to_sms "9899992980" att "nice job" -u "user@externalserver.com" -p "mypassword*"

also iam trying to use a command like this since these deafault command on the page dosent seem to be working
MailToSMS( , "att", "username", "password", "hello world!", yagmail=["smtp.gmail.com", "587"])
it pops up a charactrer error in cmd like below
dquote> 

i dont know if this tool still works thou

**Comment by naschorr** [comment]
Hey there!

Honestly I haven't tested MailToSMS with a non Gmail mail service, so I can't directly comment on that. However yagmail (the SMTP client that's used here) does support arbitrary SMTP servers. Looking at the docs, it looks like a command like this one would work?

```
MailToSMS("your phone number" , "att", "your username", "your password", "hello world!", yagmail=["your SMTP server's address", "your SMTP service's port"])
```

I also just tested the hello world examples and they worked just fine (credentials redacted, of course)
```
from mail_to_sms import MailToSMS
MailToSMS("my phone number", "t-mobile", "my gmail username", "my gmail app password", "hello world!")
```
```
from mail_to_sms import MailToSMS
MailToSMS("my phone number", "t-mobile", "my gmail username", "my gmail app password", "hello world!", yagmail=["smtp.gmail.com", "587"])
```

Could you provide the exact error that pops up when you try and run those commands? Or was it literally just `dquote>`?

**Comment by naschorr** [comment]
Closing this for now, feel free to reopen in the future.
